Table users {
  id uuid [primary key]
  name varchar [not null]
  email varchar [not null]
  password varchar [not null]
  role varchar // kira kira apa ya
  created_at timestamp
}

Table documents {
  id uuid [primary key]
  file_name varchar
  file_extension varchar //
  file_type varchar // invoice or bank statement
  file_url varchar // connect ke drive
  uploaded_by uuid [ref: > users.id]
  uploaded_at timestamp
}

Table transactions_business {
  id uuid [primary key]
  document_id uuid [ref: > documents.id]
  invoice_number varchar // no faktur
  transaction_date date [not null]
  vendor varchar [not null]
  amount decimal [not null]
  coa varchar [not null]
  score_ai float
  status varchar [note: 'pending | approved | rejected']
  created_at timestamp
}

Table business_ai_confidence {
  id uuid [primary key]
  transaction_id uuid [not null, ref: > transactions_business.id]
  confidence_score float
  confidence_level varchar
  coa_recommendation varchar
  history_match_score float
  history_match_weight float
  history_match_reason text
  vendor_match_score float
  vendor_match_weight float
  vendor_match_reason text
  amount_pattern_score float
  amount_pattern_weight float
  amount_pattern_historical_average decimal
  amount_pattern_difference_percentage float
  amount_pattern_reason text
  keyword_match_score float
  keyword_match_weight float
  keyword_match_reason text
  frequency_pattern_score float
  frequency_pattern_weight float
  frequency_pattern_reason text
  summary_most_similar_transaction varchar
  summary_risk_level varchar
  summary_recommendation text
  summary_invoice_type_prediction varchar
  created_at timestamp
}